### ISSUE TITLE
이슈 등록/처리 프로세스 숙지

### ISSUE THREAD

**Issue by 365kim** [42-JMJ/iOS-App-Project#1]
https://github.com/42-JMJ/iOS-App-Project/projects/2   < 여기서 관리합니다
![project](https://user-images.githubusercontent.com/60066472/79728104-5a970a80-8328-11ea-9ae9-78b25b629b2e.JPG)

**1. 신규 Issue / 할일**
- 작업해야 될 이슈들
- 이슈 생성 시 자동으로 등록됩니다

**2. 진행중 / 코드 작성중**
- PR 전이지만 작업에 착수한 것
- 수동으로 옮겨주세요

**3.  PR완료 / 리뷰 대기중**
- PR 을 끝내고 리뷰어 2명의 리뷰를 기다리는 이슈
- PR시 자동으로 옮겨집니다

**4. 리뷰어 승인완료 / merge 대기중**
- 리뷰어 2명의 승인을 받았지만 아직 merge 하지 않은 이슈
- 리뷰어 승인 완료시 자동으로 옮겨집니다

**5.  merge 완료 / issue 종결**
- merge 완료한 이슈 또는 merge가 필요없고 종결된 이슈
- 이슈 close 하거나 merge하는 경우 자동으로 옮겨집니다

**Comment by robolovo** [comment]
갓-갓 이제 말하기도 입아프다.. 갓..(_o_)
