### ISSUE TITLE
앱 화면 순서도

### ISSUE THREAD

**Issue by robolovo** [42-JMJ/iOS-App-Project#2]
![KakaoTalk_Photo_git issue](https://user-images.githubusercontent.com/55264231/79740826-40b2f300-833b-11ea-97e5-bb3cffdc6c22.png)

**Comment by 365kim** [comment]
와~~~ 좋은거 같아요!
그런데 3주밖에 없으니까 #5, #6은 추가기능 후보로만 빼두고 나머지를 먼저 구현할까요?
추가기능으로 잠금기능도 생각해봤어요
