### ISSUE TITLE
DB를 Realm에서 Sqlite3로 변경합니다

### ISSUE THREAD

**Issue by dev-jko** [42-JMJ/iOS-App-Project#21]
클러스터 아이맥에서 코코아팟과 라이브러리 설치가 불가능하여 DB를 sqlite3로 변경하기로 하였습니다

**Comment by 365kim** [comment]
확인했습니다 감사합니다 👍 👍 👍 👍 
light한 sqlite 고고!

**Comment by robolovo** [comment]
고생하셨어요! 👍 👍 👍
