### ISSUE TITLE
 LaunchScreen 디자인 시안입니다 (논의해보고 반영)

### ISSUE THREAD

**Issue by robolovo** [42-JMJ/iOS-App-Project#24]
#22 관련 _LaunchScreen_ 디자인 시안입니다
현재 총 6가지 작성해보았습니다
자유롭게 의견주시고 논의해서 최종안 결정되면 PR에 반영하도록 하겠습니다
## 1번 시안
<p align="center"><img src="https://user-images.githubusercontent.com/60066472/80386945-028d7480-88e3-11ea-9627-1b4d47a5c3a4.png" width="250"></p>

## 2번 시안
<p align="center"><img src="https://user-images.githubusercontent.com/60066472/80386951-04573800-88e3-11ea-9664-9f70c612aaa9.png" width="250"></p>

## 3번 시안
<p align="center"><img src="https://user-images.githubusercontent.com/60066472/80386956-0620fb80-88e3-11ea-8072-e2a6b37f3d30.png" width="250"></p>

## 4번 시안
<p align="center"><img src="https://user-images.githubusercontent.com/60066472/80386960-07522880-88e3-11ea-9e1f-a05fc88fcddd.png" width="250"></p>

## 5번 시안
<p align="center"><img src="https://user-images.githubusercontent.com/60066472/80386961-07eabf00-88e3-11ea-9bed-0e8656383b07.png" width="250"></p>

## 6번 시안
<p align="center"><img src="https://user-images.githubusercontent.com/60066472/80386967-09b48280-88e3-11ea-917f-51141548ab95.png" width="250"></p>
<a href="#top">맨 위로</a>

**Comment by 365kim** [comment]
이 중에 하나만 골라야 하는거라면 너무 잔인합니다.. 다 너무 예쁩니다 !!!
앱의 컨텐츠가 담고 있는 감성을 잘 나타내는 것 같아요!

**Comment by 365kim** [comment]
저는 굳이 굳이 꼽자면 🥇 __4번, 5번__ 🥇  을 뽑겠습니다
