### ISSUE TITLE
데이터베이스 싱글톤으로 사용하게 변경

### ISSUE THREAD

**Issue by dev-jko** [42-JMJ/iOS-App-Project#26]
- 테스트 디비와 sqlite 디비 연결을 딱 1개만 하기 위해서 싱글톤 패턴으로 만들었습니다

## 사용방법
```
let db: DataBase = TestDataBase.instance
db.selectArticle(date)
db.updateArticle(article)
```

**Comment by 365kim** [comment]
사용방법까지 친절하게! 감사합니당 👍 왕-땅콩 👍

**Comment by 365kim** [comment]
디자인패턴 흘려듣기만 했는데 덕분에 개념을 접하게되었습니다 감사합니다
![dp](https://user-images.githubusercontent.com/60066472/80556291-15509800-8a0e-11ea-805d-c641c197f382.png)
