### ISSUE TITLE
일정 수립

### ISSUE THREAD

**Issue by dev-jko** [42-JMJ/iOS-App-Project#3]
![스크린샷 2020-04-20 오후 7 41 10](https://user-images.githubusercontent.com/31630051/79743258-398de400-833f-11ea-8976-1930dbf6580f.png)

프로젝트 일정표입니다!

**Comment by 365kim** [comment]
와아~~ 감사합니다 !!
변경 사항은 그때그때 같이 수정하면서 진행하면 될거같아요!

**Comment by 365kim** [comment]
![loca](https://user-images.githubusercontent.com/60066472/79744293-0c423580-8341-11ea-8931-9bffe3a2ad41.png)
위키탭에 링크 추가해두었습니다
