### ISSUE TITLE
협업 중 충돌방지를 위한 파일설정

### ISSUE THREAD

**Issue by dev-jko** [42-JMJ/iOS-App-Project#5]
xcode로 iOS 프로젝트를 생성하고 스토리보드를 연결해주세요

**Comment by 365kim** [comment]
프로젝트명 OneDayOneAnswer 으로 생성하고
file - New -file - Storyboard 로 3명이 각각 작업할 서브 스토리보드를 추가하였습니다

**Comment by 365kim** [comment]
새로 생성한 서브 스토리보드에 뷰컨트롤러를 추가한 외에 다른 옵션은 수정하지 않은 채로 PR 올렸습니다. 혹시 다른 옵션지정이 선행되야 하는지는 확실하게 모르겠습니다...
