### ISSUE TITLE
sqlite에 이미지를 저장해야합니다

### ISSUE THREAD

**Issue by dev-jko** [42-JMJ/iOS-App-Project#50]
이미지를 저장할 id, image로 이루어진 테이블을 새로 생성하고
아티클에 연관된 이미지 id를 추가할 예정입니다

이미지가 이미 저장된(중복된) 이미지인지 검사하여 중복 저장을 막아야할지 고민 중입니다

**Comment by dev-jko** [comment]
https://yagom.net/forums/topic/%EC%9D%B4%EB%AF%B8%EC%A7%80-%EC%A0%80%EC%9E%A5-%EB%82%B4%EB%B6%80db-%EC%A7%88%EB%AC%B8-%EB%93%9C%EB%A6%BD%EB%8B%88%EB%8B%A4-2/

아티클에 이미지 경로를 추가하고 테이블은 새로 생성하지 않아도 될 것 같습니다

**Comment by dev-jko** [comment]
사용 예시
```
        let img: UIImage = 이미지

        // 저장
        guard let fileName: String = saveUIImageToDocDir(image: img) else {
            print("save error")
            return
        }

        print(fileName) // article.imagePath에 넣을 값

        // 불러오기
        guard let img2: UIImage = getUIImageFromDocDir(fileName: fileName) else {
            print("load error")
            return
        }

        myUIImageView.image = img2
```

**Comment by 365kim** [comment]
항상 사용법까지 친절하게 올려주셔서 감사합니다~~~ :)
